---

- name: Setup all servers
  hosts: all
  become: true
  become_user: root
  roles:
    - role: sysinfo
    - role: environment

- name: Setup api h5radar servers
  hosts: api_h5radar_servers
  become: true
  become_user: root
  roles:
    - role: hello_world
    - role: openjdk
    - role: maven
    # - role: apache
    # - role: h5radar_api

- name: Setup app h5radar servers
  hosts: app_h5radar_servers
  become: true
  become_user: root
  roles:
    - role: hello_world
    - role: js_env
    # - role: apache
    # - role: h5radar_app
