---

- name: Setup all servers
  hosts: all
  become: true
  become_user: root
  roles:
    - role: sysinfo
    - role: environment
    - role: workstation

- name: Setup api h5radar servers
  hosts: api_h5radar_servers
  become: true
  become_user: root
  roles:
    - role: firewall
    - role: openjdk
    - role: apache
    - role: h5radar_api

- name: Setup app h5radar servers
  hosts: app_h5radar_servers
  become: true
  become_user: root
  roles:
    - role: firewall
    - role: js_env
    - role: apache
    - role: h5radar_app

- name: Setup iam h5radar servers
  hosts: iam_h5radar_servers
  become: true
  become_user: root
  roles:
    - role: firewall
    - role: openjdk
    - role: apache
    - role: h5radar_iam
