---

- name: Check os distribution for debian
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Ubuntu"
    fail_msg: "Only Ubuntu distribution is supported for Debian family"
  when:
    - ansible_os_family == "Debian"

- name: Check os distribution version for ubuntu
  ansible.builtin.assert:
    that:
      - ansible_distribution_major_version | int  >= 24
    fail_msg: "Only Ubuntu distribution 24+ is supported for Debian family"
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution  == "Ubuntu"

- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes
  when:
    - ansible_os_family == 'Debian'
