---

- name: Reload apache
  ansible.builtin.service:
    name: "{{ h5radar_app__apache_service_map[ansible_os_family] }}"
    state: reloaded

- name: Restart apache
  ansible.builtin.service:
    name: "{{ h5radar_app__apache_service_map[ansible_os_family] }}"
    state: restarted
