---

# Logging configuration to avoid output sensitive information.
h5radar_api__no_log: false

#
# Settings section
#
h5radar_api__domain: "{{ inventory_hostname }}"
h5radar_api__mail: "hostmaster@{{ inventory_hostname | replace('api.', '') }}"
h5radar_api__cert_type: "letsencrypt"
h5radar_api__google_analytics: '{{ lookup("env", "google_analytics") or "G-1X9CQ8HG2W" }}'
h5radar_api__yandex_metrika: '{{ lookup("env", "yandex_metrika") or "99576263" }}'

#
# Database section
# App adapter can be: postgresql, mysql2, sqlite
#
h5radar_api__db_adapter: "postgresql"
h5radar_api__db_host: "127.0.0.1"
h5radar_api__db_name: "h5radar_radar"
h5radar_api__db_user: "h5radar_radar_user"
h5radar_api__db_password: '{{ lookup("env", "H5RADAR_RADAR_DATABASE_PASSWORD") or "secret" }}'

#
# SMTP section
#
h5radar_api__smtp_address: "mail.h5radar.com"
h5radar_api__smtp_domain: "h5radar.com"
h5radar_api__smtp_port: "25"
h5radar_api__smtp_user_name: "support@h5radar.com"
h5radar_api__smtp_user_password: '{{ lookup("env", "support_mail_password") or "secret" }}'

#
# Deploy section
#
h5radar_api__user: "h5radar_api"
h5radar_api__group: "h5radar_api"
h5radar_api__version: "v0.0.3"
h5radar_api__binaries: "https://github.com/h5radar/radar/releases/download/{{ h5radar_api__version }}/Binaries.tar.gz"
h5radar_api__root_path: '/home/{{ h5radar_api__user }}'
h5radar_api__shared_path: "{{ h5radar_api__root_path }}/shared"
h5radar_api__current_path: "{{ h5radar_api__root_path }}/current"
h5radar_api__release_path: "{{ h5radar_api__root_path }}/releases/radar/{{ ansible_date_time.iso8601_basic_short }}"
h5radar_api__keep_releases: 2
h5radar_api__tomcat_port: 8080
h5radar_api__service_units:
  - h5radar_radar
h5radar_api__letsencrypt_hooks:
  - api_h5radar_apache
  - api_h5radar_radar
