---

- name: Check os family
  ansible.builtin.assert:
    that:
      - ansible_os_family == "Debian" or ansible_os_family == "RedHat"
    fail_msg: "Only Debian, RedHat family are supported"

- name: Import rules for os family
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
