---

- name: cat /etc/os-release file
  ansible.builtin.command: "/bin/cat /etc/os-release"
  register: result
  changed_when: false

- name: output /etc/os-release file
  ansible.builtin.debug:
    - msg="{{ result.stdout_lines }}"

- name: cat /etc/hosts file
  ansible.builtin.command: "/bin/cat /etc/hosts"
  register: result
  changed_when: false

- name: output /etc/hosts file
  ansible.builtin.debug:
    - msg="{{ result.stdout_lines }}"
