---

dependencies:
  - role: users
    users__dependent_accounts:
      - name: "{{ h5radar_app__user }}"
        state: "present"
        group: "{{ h5radar_app__group }}"
        system: true
        shell: "/bin/bash"
        sshkeys: []
  - role: certbot
    certbot__cert_type: "{{ h5radar_app__cert_type }}"
    certbot__mail: "{{ h5radar_app__mail }}"
    certbot__domains:
      - name: "{{ h5radar_app__domain }}"
        aliases: []
