---

dependencies:
  - role: users
    users__dependent_accounts:
      - name:   '{{ h5radar_iam__user }}'
        state:  'present'
        group:  '{{ h5radar_iam__group }}'
        system: True
        shell: '/bin/bash'
        sshkeys: []
        sudo:
          - "{{ h5radar_iam__user }} ALL=(ALL) NOPASSWD: ALL"
  - role: certbot
    certbot__cert_type: "{{ h5radar_iam__cert_type }}"
    certbot__mail: "{{ h5radar_iam__mail }}"
    certbot__domains:
      - name: "{{ h5radar_iam__domain }}"
        aliases: []
  - role: postgresql
    postgresql__pg_hba:
      - contype: "host"
        databases: "{{ h5radar_iam__db_name }}"
        users: "{{ h5radar_iam__db_user }}"
        source: "127.0.0.1/32"
        method: "md5"
    postgresql__roles:
      - name: "{{ h5radar_iam__db_user }}"
        password: "{{ h5radar_iam__db_password }}"
        login_db: "{{ h5radar_iam__db_name }}"
        priv: "ALL"
    postgresql__databases:
      - name: "{{ h5radar_iam__db_name }}"
        owner: "{{ h5radar_iam__db_user }}"
