---

h5radar_iam__apache_service_map:
  'RedHat': "httpd"
  'Debian': "apache2"

h5radar_iam__apache_conf_map:
  'RedHat': "httpd/conf.d"
  'Debian': "apache2/sites-available"

h5radar_iam__apache_templates:
  - robots.txt

h5radar_iam__apache_statics:
  - 404.var
  - 404.en.html
  - 404.ru.html
  - 503.var
  - 503.en.html
  - 503.ru.html
  - maintenance.var
  - maintenance.en.html
  - maintenance.ru.html
  - stylesheets/bootstrap.min.css
