---

- name: Disable ufw service
  ansible.builtin.command: ufw -f disable
  register: result
  changed_when: result.rc != 0
  when: ansible_os_family == 'Debian'

- name: Disable firewalld service
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false
  when: ansible_os_family == 'RedHat'
