---

# Logging configuration to avoid output sensitive information.
h5radar_iam__no_log: false

#
# Settings section
#
h5radar_iam__domain: "{{ inventory_hostname }}"
h5radar_iam__mail: "hostmaster@{{ inventory_hostname | replace('iam.', '') }}"
h5radar_iam__cert_type: "letsencrypt"
h5radar_iam__keytool_password: "{{ lookup('env', 'JAVA_KEYTOOL_PASSWORD') or 'changeit' }}"
h5radar_iam__keycloak_version: "26.1.4"
h5radar_iam__keycloak_path: "https://github.com/keycloak/keycloak/releases/download"
h5radar_iam__keycloak_package: "{{ h5radar_iam__keycloak_path }}/{{ h5radar_iam__keycloak_version }}/keycloak-{{ h5radar_iam__keycloak_version }}.tar.gz"
h5radar_iam__keycloak_admin: "admin"
h5radar_iam__keycloak_admin_password: "{{ lookup('env', 'H5RADAR_KEYCLOAK_ADMIN_PASSWORD') or 'secret' }}"


#
# Database section
# App adapter can be: postgresql, mysql2, sqlite
#
h5radar_iam__db_adapter: "postgresql"
h5radar_iam__db_host: "127.0.0.1"
h5radar_iam__db_name: "h5radar_keycloak"
h5radar_iam__db_user: "h5radar_keycloak_user"
h5radar_iam__db_password: '{{ lookup("env", "H5RADAR_KEYCLOAK_DATABASE_PASSWORD") or "secret" }}'

#
# SMTP section
#
h5radar_iam__smtp_address: "mail.h5radar.com"
h5radar_iam__smtp_domain: "h5radar.com"
h5radar_iam__smtp_port: "25"
h5radar_iam__smtp_user_name: "support@h5radar.com"
h5radar_iam__smtp_user_password: '{{ lookup("env", "h5radar_support_mail_password") or "secret" }}'


#
# Deploy section
#
h5radar_iam__user: "h5radar_iam"
h5radar_iam__group: "h5radar_iam"
h5radar_iam__root_path: "/home/{{ h5radar_iam__user }}"
h5radar_iam__shared_path: "{{ h5radar_iam__root_path }}/shared"
h5radar_iam__current_path: "{{ h5radar_iam__root_path }}/current"
h5radar_iam__release_path: "{{ h5radar_iam__root_path }}/releases/keycloak-{{ h5radar_iam__keycloak_version }}"
h5radar_iam__keycloak_port: 8443
h5radar_iam__service_units:
  - h5radar_keycloak
h5radar_iam__letsencrypt_hooks:
  - iam_h5radar_apache
  - iam_h5radar_keycloak
