---
- name: Create directories for application
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ h5radar_app__user }}"
    group: "{{ h5radar_app__group }}"
    state: directory
    mode: "755"
  with_items:
    - "{{ h5radar_app__root_path }}/"
    - "{{ h5radar_app__root_path }}/releases"
    - "{{ h5radar_app__release_path }}"
    - "{{ h5radar_app__current_path }}/dist"

- name: Get binaries
  ansible.builtin.unarchive:
    src: "{{ h5radar_app__binaries }}"
    dest: "{{ h5radar_app__current_path }}/dist"
    remote_src: yes
