---

apache__package_map:
  'Debian':
    - apache2
    - apache2-utils
  'RedHat':
    - httpd
    - mod_ssl
    - httpd-tools

apache__module_map:
  - expires
  - headers
  - lbmethod_byrequests
  - mime_magic
  - proxy
  - proxy_balancer
  - proxy_http
  - remoteip
  - rewrite
  - ssl

apache__service_map:
  'RedHat': "httpd"
  'Debian': "apache2"
