---

h5radar_app__apache_service_map:
  'RedHat': "httpd"
  'Debian': "apache2"

h5radar_app__apache_conf_map:
  'RedHat': "httpd/conf.d"
  'Debian': "apache2/sites-available"

h5radar_app__apache_templates:
  - robots.txt
