---

- name: Configure apache sites h5radar_api
  ansible.builtin.template:
    src: "etc/httpd/conf.d/api.h5radar.tld.conf.j2"
    dest: "/etc/{{ h5radar_api__apache_conf_map[ansible_os_family] }}/{{ h5radar_api__domain }}.conf"
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - Reload apache

- name: Enable h5radar_api website
  ansible.builtin.command: "{{ item }}"
  with_items:
    - "a2ensite {{ h5radar_api__domain }}.conf"
    - "apache2ctl configtest"
  register: result
  changed_when: result.rc != 0
  when:
    - ansible_os_family == 'Debian'
  notify:
    - Reload apache

- name: Create directories for apache
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ h5radar_api__user }}"
    group: "{{ h5radar_api__group }}"
    state: directory
    mode: "755"
  with_items:
    - "{{ h5radar_api__current_path }}"
    - "{{ h5radar_api__current_path }}/public"
    - "{{ h5radar_api__current_path }}/public/stylesheets"

- name: Copy apache templates
  ansible.builtin.template:
    src: "home/h5radar_api/current/public/{{ item }}.j2"
    dest: "{{ h5radar_api__current_path }}/public/{{ item }}"
    owner: "{{ item.owner | default('h5radar_api') }}"
    group: "{{ item.group | default('h5radar_api') }}"
    mode: "0644"
  with_items:
    - "{{ h5radar_api__apache_templates }}"

- name: Copy apache static files
  ansible.builtin.copy:
    src: "files/home/h5radar_api/current/public/{{ item }}"
    dest: "{{ h5radar_api__current_path }}/public/{{ item }}"
    owner: "{{ item.owner | default('h5radar_api') }}"
    group: "{{ item.group | default('h5radar_api') }}"
    mode: "0644"
  with_items:
    - "{{ h5radar_api__apache_statics }}"
