---

- name: Stop services
  ansible.builtin.service:
    name: '{{ item }}'
    state: stopped
  with_items:
    - "{{ h5radar_api__service_units }}"

- name: Create directories for application
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ h5radar_api__user }}"
    group: "{{ h5radar_api__group }}"
    state: directory
    mode: "755"
  with_items:
    - "{{ h5radar_api__root_path }}/"
    - "{{ h5radar_api__root_path }}/releases"
    - "{{ h5radar_api__root_path }}/releases/radar"
    - "{{ h5radar_api__release_path }}/target"

- name: Get binaries
  ansible.builtin.unarchive:
    src: "{{ h5radar_api__binaries }}"
    dest: "{{ h5radar_api__release_path }}/target"
    remote_src: yes

- name: Create configuration files
  ansible.builtin.template:
    src: "home/h5radar_api/releases/radar/timestamp/target/{{ item }}.j2"
    dest: "{{ h5radar_api__release_path }}/target/{{ item }}"
    owner: "{{ h5radar_api__user | default('h5radar_api') }}"
    group: "{{ h5radar_api__user | default('h5radar_api') }}"
    mode: "0644"
  with_items:
    - application.yml

- name: Start services
  ansible.builtin.service:
    name: '{{ item }}'
    state: started
  with_items:
    - "{{ h5radar_api__service_units }}"
