---
- name: Install acl packages
  ansible.builtin.package:
    name: acl
    state: present

- name: Stop services
  ansible.builtin.service:
    name: '{{ item }}'
    state: stopped
  with_items:
    - "{{ h5radar_api__service_units }}"

- name: Create directories for application
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ h5radar_api__user }}"
    group: "{{ h5radar_api__group }}"
    state: directory
    mode: "755"
  with_items:
    - "{{ h5radar_api__root_path }}/"
    - "{{ h5radar_api__root_path }}/releases"
    - "{{ h5radar_api__root_path }}/releases/radar"
    - "{{ h5radar_api__release_path }}"

- name: Checkout git repository
  become: true
  become_user: "{{ h5radar_api__user }}"
  ansible.builtin.git:
    repo: 'https://github.com/h5radar/radar.git'
    dest: "{{ h5radar_api__release_path }}"
    version: "{{ h5radar_api__version }}"

- name: Run maven commands
  become: true
  become_user: "{{ h5radar_api__user }}"
  ansible.builtin.shell: "{{ item }}"
  environment:
    PATH: "{{ ansible_env.PATH }}"
  args:
    executable: /bin/bash
    chdir: "{{ h5radar_api__release_path }}"
  with_items:
    - mvn clean package -Dmaven.test.skip
  register: result
  changed_when: result.rc != 0

- name: Create configuration files
  ansible.builtin.template:
    src: "home/h5radar_api/releases/radar/timestamp/target/{{ item }}.j2"
    dest: "{{ h5radar_api__release_path }}/target/{{ item }}"
    owner: "{{ h5radar_api__user | default('h5radar_api') }}"
    group: "{{ h5radar_api__user | default('h5radar_api') }}"
    mode: "0644"
  with_items:
    - application.yml

- name: Keep only few last releases
  ansible.builtin.shell: "set -o pipefail && find ./ -maxdepth 1 |
          grep -G .............. |
          sort -r |
          tail -n +{{ h5radar_api__keep_releases }} |
          xargs rm -rf"
  args:
    executable: /bin/bash
    chdir: "{{ h5radar_api__root_path }}/releases/radar"
  register: result
  changed_when: result.rc != 0

- name: Start services
  ansible.builtin.service:
    name: '{{ item }}'
    state: started
  with_items:
    - "{{ h5radar_api__service_units }}"
