---

- name: stop services
  ansible.builtin.service:
    name: '{{ item }}'
    state: stopped
  with_items:
    - "{{ h5radar_api__service_units }}"

- name: Create directories for application
  file:
    path:    "{{ item }}"
    owner:   "{{ h5radar_api__user }}"
    group:   "{{ h5radar_api__group }}"
    state:   directory
    mode:    "0755"
  with_items:
    - "{{ h5radar_api__root_path }}/"
    - "{{ h5radar_api__root_path }}/releases"
    - "{{ h5radar_api__root_path }}/releases/radar"
    - "{{ h5radar_api__release_path }}"

- name: git checkout repository
  become: yes
  become_user: "{{ h5radar_api__user }}"
  git:
    repo: 'https://oauth2:{{ gitlab_pat }}@gitlab.a5lab.com/h5radar/radar.git'
    dest: "{{ h5radar_api__release_path }}"
    version: HEAD

- name: run maven commands
  become: yes
  become_user: "{{ h5radar_api__user }}"
  shell: "{{ item }}"
  environment:
    PATH: "{{ ansible_env.PATH }}"
  args:
    executable: /bin/bash
    chdir: "{{ h5radar_api__release_path }}"
  with_items:
    - mvn clean package

- name: Create configuration files
  ansible.builtin.template:
    src: "home/h5radar_api/releases/radar/timestamp/target/{{ item }}.j2"
    dest: "{{ h5radar_api__release_path }}/target/{{ item }}"
    owner: "{{ h5radar_api__user | default('h5radar_api') }}"
    group: "{{ h5radar_api__user | default('h5radar_api') }}"
    mode: "0644"
  with_items:
    - application.yml

- name: keep only few last releases
  shell: "find ./ -maxdepth 1 |
          grep -G .............. |
          sort -r |
          tail -n +{{ h5radar_api__keep_releases }} |
          xargs rm -rf"
  args:
    chdir: "{{ h5radar_api__root_path }}/releases/radar"

- name: start services
  ansible.builtin.service:
    name: '{{ item }}'
    state: started
  with_items:
    - "{{ h5radar_api__service_units }}"

