---
- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add h5radar_radar user to docker group
  ansible.builtin.user:
    name: "{{ h5radar_api__user }}"
    groups: docker
    append: true
