---

# Logging configuration to avoid output sensitive information.
h5radar_app__no_log: false

#
# Settings section
#
h5radar_app__domain: "{{ inventory_hostname }}"
h5radar_app__mail: "hostmaster@{{ inventory_hostname | replace('app.','')}}"
h5radar_app__cert_type: "letsencrypt"
h5radar_app__google_analytics: '{{ lookup("env", "google_analytics") or "G-1X9CQ8HG2W"}}'
h5radar_app__yandex_metrika: '{{ lookup("env", "yandex_metrika") or "99576263"}}'

#
# Deploy section for app
#
h5radar_app__user: "h5radar_app"
h5radar_app__group: "h5radar_app"
h5radar_app__version: "0.1.0"
h5radar_app__root_path: '/home/{{ h5radar_app__user }}'
h5radar_app__shared_path: "{{ h5radar_app__root_path }}/shared"
h5radar_app__current_path: "{{ h5radar_app__root_path }}/current"
h5radar_app__release_path: "{{ h5radar_app__root_path }}/releases/{{ ansible_date_time.iso8601_basic_short }}"
h5radar_app__keep_releases: 2

#
# Deploy section
#
h5radar_app__letsencrypt_hooks:
  - app_h5radar_apache
